from django.urls import path
from .views import (
    CursoActualEstudianteView,
    CursosPorEstudianteListView,
    AsignaturaPorCursoListView,
    ContenidoPorAsignaturaListView,
    ContenidoDetailView,
    AsignaturasPorProfesorView,
    ContenidoCreateView,
    ContenidoProfesorDetailView,
)

urlpatterns = [
    path(
        'students/<int:id_estudiante>/courses/current/',
        CursoActualEstudianteView.as_view(),
        name='current_student_course'
    ),
    path(
        'students/<int:id_student>/courses/',
        CursosPorEstudianteListView.as_view(),
        name='student_courses'
    ),
    path(
        'students/courses/<int:id_course>/subjects/',
        AsignaturaPorCursoListView.as_view(),
        name='course_subjects'
    ),
    path(
        'students/courses/subjects/<int:id_subject>/contents/',
        ContenidoPorAsignaturaListView.as_view(),
        name='subject_contents'
    ),
    path(
        'students/courses/subjects/contents/<int:pk>/',
        ContenidoDetailView.as_view(),
        name='content_detail'
    ),
    path(
        'teachers/<int:id_teacher>/subjects/',
        AsignaturasPorProfesorView.as_view(),
        name='teacher_subjects'
    ),
    path(
        'teachers/subjects/<int:asignatura>/contents/create/',
        ContenidoCreateView.as_view(),
        name='content_create'
    ),
    path(
        'teachers/subjects/<int:id_subject>/contents/',
        ContenidoPorAsignaturaListView.as_view(),
        name='subject_contents'
    ),
    path(
        'teachers/subjects/contents/<int:pk>/',
        ContenidoProfesorDetailView.as_view(),
        name='content_teacher_detail'
    ),
]
