# Generated by Django 4.2.1 on 2023-06-04 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('codigo_estudiante', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('codigo_profesor', models.CharField(max_length=10)),
            ],
        ),
    ]
